"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.trade_date import TradeDate
globals()['TradeDate'] = TradeDate
from openapi_client.model.tradovate_subscription_plan import TradovateSubscriptionPlan


class TestTradovateSubscriptionPlan(unittest.TestCase):
    """TradovateSubscriptionPlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTradovateSubscriptionPlan(self):
        """Test TradovateSubscriptionPlan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TradovateSubscriptionPlan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
