"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.second_market_data_subscription_cost_response import SecondMarketDataSubscriptionCostResponse


class TestSecondMarketDataSubscriptionCostResponse(unittest.TestCase):
    """SecondMarketDataSubscriptionCostResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecondMarketDataSubscriptionCostResponse(self):
        """Test SecondMarketDataSubscriptionCostResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecondMarketDataSubscriptionCostResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
