"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.risks_api import RisksApi  # noqa: E501


class TestRisksApi(unittest.TestCase):
    """RisksApi unit test stubs"""

    def setUp(self):
        self.api = RisksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contract_margin_dependents(self):
        """Test case for contract_margin_dependents

        """
        pass

    def test_contract_margin_item(self):
        """Test case for contract_margin_item

        """
        pass

    def test_contract_margin_items(self):
        """Test case for contract_margin_items

        """
        pass

    def test_contract_margin_l_dependents(self):
        """Test case for contract_margin_l_dependents

        """
        pass

    def test_delete_user_account_position_limit(self):
        """Test case for delete_user_account_position_limit

        """
        pass

    def test_delete_user_account_risk_parameter(self):
        """Test case for delete_user_account_risk_parameter

        """
        pass

    def test_product_margin_dependents(self):
        """Test case for product_margin_dependents

        """
        pass

    def test_product_margin_item(self):
        """Test case for product_margin_item

        """
        pass

    def test_product_margin_items(self):
        """Test case for product_margin_items

        """
        pass

    def test_product_margin_l_dependents(self):
        """Test case for product_margin_l_dependents

        """
        pass

    def test_product_margin_list(self):
        """Test case for product_margin_list

        """
        pass

    def test_user_account_auto_liq_create(self):
        """Test case for user_account_auto_liq_create

        """
        pass

    def test_user_account_auto_liq_dependents(self):
        """Test case for user_account_auto_liq_dependents

        """
        pass

    def test_user_account_auto_liq_item(self):
        """Test case for user_account_auto_liq_item

        """
        pass

    def test_user_account_auto_liq_items(self):
        """Test case for user_account_auto_liq_items

        """
        pass

    def test_user_account_auto_liq_l_dependents(self):
        """Test case for user_account_auto_liq_l_dependents

        """
        pass

    def test_user_account_auto_liq_list(self):
        """Test case for user_account_auto_liq_list

        """
        pass

    def test_user_account_auto_liq_update(self):
        """Test case for user_account_auto_liq_update

        """
        pass

    def test_user_account_position_limit_create(self):
        """Test case for user_account_position_limit_create

        """
        pass

    def test_user_account_position_limit_dependents(self):
        """Test case for user_account_position_limit_dependents

        """
        pass

    def test_user_account_position_limit_item(self):
        """Test case for user_account_position_limit_item

        """
        pass

    def test_user_account_position_limit_items(self):
        """Test case for user_account_position_limit_items

        """
        pass

    def test_user_account_position_limit_l_dependents(self):
        """Test case for user_account_position_limit_l_dependents

        """
        pass

    def test_user_account_position_limit_update(self):
        """Test case for user_account_position_limit_update

        """
        pass

    def test_user_account_risk_parameter_create(self):
        """Test case for user_account_risk_parameter_create

        """
        pass

    def test_user_account_risk_parameter_dependents(self):
        """Test case for user_account_risk_parameter_dependents

        """
        pass

    def test_user_account_risk_parameter_item(self):
        """Test case for user_account_risk_parameter_item

        """
        pass

    def test_user_account_risk_parameter_items(self):
        """Test case for user_account_risk_parameter_items

        """
        pass

    def test_user_account_risk_parameter_l_dependents(self):
        """Test case for user_account_risk_parameter_l_dependents

        """
        pass

    def test_user_account_risk_parameter_update(self):
        """Test case for user_account_risk_parameter_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
