"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.user_plugin import UserPlugin
globals()['UserPlugin'] = UserPlugin
from openapi_client.model.entitlement_subscription_response import EntitlementSubscriptionResponse


class TestEntitlementSubscriptionResponse(unittest.TestCase):
    """EntitlementSubscriptionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntitlementSubscriptionResponse(self):
        """Test EntitlementSubscriptionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntitlementSubscriptionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
