"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account import Account
from openapi_client.model.cash_balance import CashBalance
from openapi_client.model.command import Command
from openapi_client.model.command_report import CommandReport
from openapi_client.model.contract import Contract
from openapi_client.model.contract_group import ContractGroup
from openapi_client.model.contract_maturity import ContractMaturity
from openapi_client.model.currency import Currency
from openapi_client.model.exchange import Exchange
from openapi_client.model.execution_report import ExecutionReport
from openapi_client.model.fill import Fill
from openapi_client.model.fill_pair import FillPair
from openapi_client.model.margin_snapshot import MarginSnapshot
from openapi_client.model.model_property import ModelProperty
from openapi_client.model.order import Order
from openapi_client.model.order_strategy import OrderStrategy
from openapi_client.model.order_strategy_link import OrderStrategyLink
from openapi_client.model.order_strategy_type import OrderStrategyType
from openapi_client.model.order_version import OrderVersion
from openapi_client.model.position import Position
from openapi_client.model.product import Product
from openapi_client.model.spread_definition import SpreadDefinition
from openapi_client.model.user import User
from openapi_client.model.user_account_auto_liq import UserAccountAutoLiq
from openapi_client.model.user_plugin import UserPlugin
from openapi_client.model.user_property import UserProperty
globals()['Account'] = Account
globals()['CashBalance'] = CashBalance
globals()['Command'] = Command
globals()['CommandReport'] = CommandReport
globals()['Contract'] = Contract
globals()['ContractGroup'] = ContractGroup
globals()['ContractMaturity'] = ContractMaturity
globals()['Currency'] = Currency
globals()['Exchange'] = Exchange
globals()['ExecutionReport'] = ExecutionReport
globals()['Fill'] = Fill
globals()['FillPair'] = FillPair
globals()['MarginSnapshot'] = MarginSnapshot
globals()['ModelProperty'] = ModelProperty
globals()['Order'] = Order
globals()['OrderStrategy'] = OrderStrategy
globals()['OrderStrategyLink'] = OrderStrategyLink
globals()['OrderStrategyType'] = OrderStrategyType
globals()['OrderVersion'] = OrderVersion
globals()['Position'] = Position
globals()['Product'] = Product
globals()['SpreadDefinition'] = SpreadDefinition
globals()['User'] = User
globals()['UserAccountAutoLiq'] = UserAccountAutoLiq
globals()['UserPlugin'] = UserPlugin
globals()['UserProperty'] = UserProperty
from openapi_client.model.sync_message import SyncMessage


class TestSyncMessage(unittest.TestCase):
    """SyncMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSyncMessage(self):
        """Test SyncMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SyncMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
