"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.start_order_strategy import StartOrderStrategy


class TestStartOrderStrategy(unittest.TestCase):
    """StartOrderStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStartOrderStrategy(self):
        """Test StartOrderStrategy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StartOrderStrategy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
