"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.positions_api import PositionsApi  # noqa: E501


class TestPositionsApi(unittest.TestCase):
    """PositionsApi unit test stubs"""

    def setUp(self):
        self.api = PositionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fill_pair_dependents(self):
        """Test case for fill_pair_dependents

        """
        pass

    def test_fill_pair_item(self):
        """Test case for fill_pair_item

        """
        pass

    def test_fill_pair_items(self):
        """Test case for fill_pair_items

        """
        pass

    def test_fill_pair_l_dependents(self):
        """Test case for fill_pair_l_dependents

        """
        pass

    def test_fill_pair_list(self):
        """Test case for fill_pair_list

        """
        pass

    def test_position_dependents(self):
        """Test case for position_dependents

        """
        pass

    def test_position_find(self):
        """Test case for position_find

        """
        pass

    def test_position_item(self):
        """Test case for position_item

        """
        pass

    def test_position_items(self):
        """Test case for position_items

        """
        pass

    def test_position_l_dependents(self):
        """Test case for position_l_dependents

        """
        pass

    def test_position_list(self):
        """Test case for position_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
