"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.chat_api import ChatApi  # noqa: E501


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self):
        self.api = ChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chat_dependents(self):
        """Test case for chat_dependents

        """
        pass

    def test_chat_item(self):
        """Test case for chat_item

        """
        pass

    def test_chat_items(self):
        """Test case for chat_items

        """
        pass

    def test_chat_l_dependents(self):
        """Test case for chat_l_dependents

        """
        pass

    def test_chat_list(self):
        """Test case for chat_list

        """
        pass

    def test_chat_message_dependents(self):
        """Test case for chat_message_dependents

        """
        pass

    def test_chat_message_item(self):
        """Test case for chat_message_item

        """
        pass

    def test_chat_message_items(self):
        """Test case for chat_message_items

        """
        pass

    def test_chat_message_l_dependents(self):
        """Test case for chat_message_l_dependents

        """
        pass

    def test_close_chat(self):
        """Test case for close_chat

        """
        pass

    def test_mark_as_read_chat_message(self):
        """Test case for mark_as_read_chat_message

        """
        pass

    def test_post_chat_message(self):
        """Test case for post_chat_message

        """
        pass


if __name__ == '__main__':
    unittest.main()
