"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.open_demo_account import OpenDemoAccount


class TestOpenDemoAccount(unittest.TestCase):
    """OpenDemoAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenDemoAccount(self):
        """Test OpenDemoAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OpenDemoAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
