"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sign_up_organization_member import SignUpOrganizationMember


class TestSignUpOrganizationMember(unittest.TestCase):
    """SignUpOrganizationMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignUpOrganizationMember(self):
        """Test SignUpOrganizationMember"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SignUpOrganizationMember()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
