"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.orders_api import OrdersApi  # noqa: E501


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_order(self):
        """Test case for cancel_order

        """
        pass

    def test_command_dependents(self):
        """Test case for command_dependents

        """
        pass

    def test_command_item(self):
        """Test case for command_item

        """
        pass

    def test_command_items(self):
        """Test case for command_items

        """
        pass

    def test_command_l_dependents(self):
        """Test case for command_l_dependents

        """
        pass

    def test_command_list(self):
        """Test case for command_list

        """
        pass

    def test_command_report_dependents(self):
        """Test case for command_report_dependents

        """
        pass

    def test_command_report_item(self):
        """Test case for command_report_item

        """
        pass

    def test_command_report_items(self):
        """Test case for command_report_items

        """
        pass

    def test_command_report_l_dependents(self):
        """Test case for command_report_l_dependents

        """
        pass

    def test_command_report_list(self):
        """Test case for command_report_list

        """
        pass

    def test_execution_report_dependents(self):
        """Test case for execution_report_dependents

        """
        pass

    def test_execution_report_find(self):
        """Test case for execution_report_find

        """
        pass

    def test_execution_report_item(self):
        """Test case for execution_report_item

        """
        pass

    def test_execution_report_items(self):
        """Test case for execution_report_items

        """
        pass

    def test_execution_report_l_dependents(self):
        """Test case for execution_report_l_dependents

        """
        pass

    def test_execution_report_list(self):
        """Test case for execution_report_list

        """
        pass

    def test_execution_report_suggest(self):
        """Test case for execution_report_suggest

        """
        pass

    def test_fill_dependents(self):
        """Test case for fill_dependents

        """
        pass

    def test_fill_fee_dependents(self):
        """Test case for fill_fee_dependents

        """
        pass

    def test_fill_fee_item(self):
        """Test case for fill_fee_item

        """
        pass

    def test_fill_fee_items(self):
        """Test case for fill_fee_items

        """
        pass

    def test_fill_fee_l_dependents(self):
        """Test case for fill_fee_l_dependents

        """
        pass

    def test_fill_fee_list(self):
        """Test case for fill_fee_list

        """
        pass

    def test_fill_item(self):
        """Test case for fill_item

        """
        pass

    def test_fill_items(self):
        """Test case for fill_items

        """
        pass

    def test_fill_l_dependents(self):
        """Test case for fill_l_dependents

        """
        pass

    def test_fill_list(self):
        """Test case for fill_list

        """
        pass

    def test_interrupt_order_strategy(self):
        """Test case for interrupt_order_strategy

        """
        pass

    def test_liquidate_position(self):
        """Test case for liquidate_position

        """
        pass

    def test_modify_order(self):
        """Test case for modify_order

        """
        pass

    def test_modify_order_strategy(self):
        """Test case for modify_order_strategy

        """
        pass

    def test_order_dependents(self):
        """Test case for order_dependents

        """
        pass

    def test_order_item(self):
        """Test case for order_item

        """
        pass

    def test_order_items(self):
        """Test case for order_items

        """
        pass

    def test_order_l_dependents(self):
        """Test case for order_l_dependents

        """
        pass

    def test_order_list(self):
        """Test case for order_list

        """
        pass

    def test_order_strategy_dependents(self):
        """Test case for order_strategy_dependents

        """
        pass

    def test_order_strategy_item(self):
        """Test case for order_strategy_item

        """
        pass

    def test_order_strategy_items(self):
        """Test case for order_strategy_items

        """
        pass

    def test_order_strategy_l_dependents(self):
        """Test case for order_strategy_l_dependents

        """
        pass

    def test_order_strategy_link_dependents(self):
        """Test case for order_strategy_link_dependents

        """
        pass

    def test_order_strategy_link_item(self):
        """Test case for order_strategy_link_item

        """
        pass

    def test_order_strategy_link_items(self):
        """Test case for order_strategy_link_items

        """
        pass

    def test_order_strategy_link_l_dependents(self):
        """Test case for order_strategy_link_l_dependents

        """
        pass

    def test_order_strategy_link_list(self):
        """Test case for order_strategy_link_list

        """
        pass

    def test_order_strategy_list(self):
        """Test case for order_strategy_list

        """
        pass

    def test_order_version_dependents(self):
        """Test case for order_version_dependents

        """
        pass

    def test_order_version_item(self):
        """Test case for order_version_item

        """
        pass

    def test_order_version_items(self):
        """Test case for order_version_items

        """
        pass

    def test_order_version_l_dependents(self):
        """Test case for order_version_l_dependents

        """
        pass

    def test_order_version_list(self):
        """Test case for order_version_list

        """
        pass

    def test_place_oco(self):
        """Test case for place_oco

        """
        pass

    def test_place_order(self):
        """Test case for place_order

        """
        pass

    def test_place_oso(self):
        """Test case for place_oso

        """
        pass

    def test_start_order_strategy(self):
        """Test case for start_order_strategy

        """
        pass


if __name__ == '__main__':
    unittest.main()
