"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.trade_date import TradeDate
globals()['TradeDate'] = TradeDate
from openapi_client.model.cash_balance_log import CashBalanceLog


class TestCashBalanceLog(unittest.TestCase):
    """CashBalanceLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashBalanceLog(self):
        """Test CashBalanceLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CashBalanceLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
