"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.fees_api import FeesApi  # noqa: E501


class TestFeesApi(unittest.TestCase):
    """FeesApi unit test stubs"""

    def setUp(self):
        self.api = FeesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_market_data_subscription_exchange_scope_find(self):
        """Test case for market_data_subscription_exchange_scope_find

        """
        pass

    def test_market_data_subscription_exchange_scope_item(self):
        """Test case for market_data_subscription_exchange_scope_item

        """
        pass

    def test_market_data_subscription_exchange_scope_items(self):
        """Test case for market_data_subscription_exchange_scope_items

        """
        pass

    def test_market_data_subscription_exchange_scope_list(self):
        """Test case for market_data_subscription_exchange_scope_list

        """
        pass

    def test_market_data_subscription_exchange_scope_suggest(self):
        """Test case for market_data_subscription_exchange_scope_suggest

        """
        pass

    def test_market_data_subscription_plan_find(self):
        """Test case for market_data_subscription_plan_find

        """
        pass

    def test_market_data_subscription_plan_item(self):
        """Test case for market_data_subscription_plan_item

        """
        pass

    def test_market_data_subscription_plan_items(self):
        """Test case for market_data_subscription_plan_items

        """
        pass

    def test_market_data_subscription_plan_list(self):
        """Test case for market_data_subscription_plan_list

        """
        pass

    def test_market_data_subscription_plan_suggest(self):
        """Test case for market_data_subscription_plan_suggest

        """
        pass

    def test_tradovate_subscription_plan_find(self):
        """Test case for tradovate_subscription_plan_find

        """
        pass

    def test_tradovate_subscription_plan_item(self):
        """Test case for tradovate_subscription_plan_item

        """
        pass

    def test_tradovate_subscription_plan_items(self):
        """Test case for tradovate_subscription_plan_items

        """
        pass

    def test_tradovate_subscription_plan_list(self):
        """Test case for tradovate_subscription_plan_list

        """
        pass

    def test_tradovate_subscription_plan_suggest(self):
        """Test case for tradovate_subscription_plan_suggest

        """
        pass


if __name__ == '__main__':
    unittest.main()
