"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.o_auth_token_response import OAuthTokenResponse


class TestOAuthTokenResponse(unittest.TestCase):
    """OAuthTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuthTokenResponse(self):
        """Test OAuthTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OAuthTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
