"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.accounting_api import AccountingApi  # noqa: E501


class TestAccountingApi(unittest.TestCase):
    """AccountingApi unit test stubs"""

    def setUp(self):
        self.api = AccountingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_dependents(self):
        """Test case for account_dependents

        """
        pass

    def test_account_find(self):
        """Test case for account_find

        """
        pass

    def test_account_item(self):
        """Test case for account_item

        """
        pass

    def test_account_items(self):
        """Test case for account_items

        """
        pass

    def test_account_l_dependents(self):
        """Test case for account_l_dependents

        """
        pass

    def test_account_list(self):
        """Test case for account_list

        """
        pass

    def test_account_suggest(self):
        """Test case for account_suggest

        """
        pass

    def test_cash_balance_dependents(self):
        """Test case for cash_balance_dependents

        """
        pass

    def test_cash_balance_item(self):
        """Test case for cash_balance_item

        """
        pass

    def test_cash_balance_items(self):
        """Test case for cash_balance_items

        """
        pass

    def test_cash_balance_l_dependents(self):
        """Test case for cash_balance_l_dependents

        """
        pass

    def test_cash_balance_list(self):
        """Test case for cash_balance_list

        """
        pass

    def test_cash_balance_log_dependents(self):
        """Test case for cash_balance_log_dependents

        """
        pass

    def test_cash_balance_log_item(self):
        """Test case for cash_balance_log_item

        """
        pass

    def test_cash_balance_log_items(self):
        """Test case for cash_balance_log_items

        """
        pass

    def test_cash_balance_log_l_dependents(self):
        """Test case for cash_balance_log_l_dependents

        """
        pass

    def test_get_cash_balance_snapshot(self):
        """Test case for get_cash_balance_snapshot

        """
        pass

    def test_margin_snapshot_dependents(self):
        """Test case for margin_snapshot_dependents

        """
        pass

    def test_margin_snapshot_item(self):
        """Test case for margin_snapshot_item

        """
        pass

    def test_margin_snapshot_items(self):
        """Test case for margin_snapshot_items

        """
        pass

    def test_margin_snapshot_l_dependents(self):
        """Test case for margin_snapshot_l_dependents

        """
        pass

    def test_margin_snapshot_list(self):
        """Test case for margin_snapshot_list

        """
        pass

    def test_trading_permission_dependents(self):
        """Test case for trading_permission_dependents

        """
        pass

    def test_trading_permission_item(self):
        """Test case for trading_permission_item

        """
        pass

    def test_trading_permission_items(self):
        """Test case for trading_permission_items

        """
        pass

    def test_trading_permission_l_dependents(self):
        """Test case for trading_permission_l_dependents

        """
        pass

    def test_trading_permission_list(self):
        """Test case for trading_permission_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
