"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.add_entitlement_subscription import AddEntitlementSubscription


class TestAddEntitlementSubscription(unittest.TestCase):
    """AddEntitlementSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddEntitlementSubscription(self):
        """Test AddEntitlementSubscription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddEntitlementSubscription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
