"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.contract_library_api import ContractLibraryApi  # noqa: E501


class TestContractLibraryApi(unittest.TestCase):
    """ContractLibraryApi unit test stubs"""

    def setUp(self):
        self.api = ContractLibraryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contract_dependents(self):
        """Test case for contract_dependents

        """
        pass

    def test_contract_find(self):
        """Test case for contract_find

        """
        pass

    def test_contract_group_find(self):
        """Test case for contract_group_find

        """
        pass

    def test_contract_group_item(self):
        """Test case for contract_group_item

        """
        pass

    def test_contract_group_items(self):
        """Test case for contract_group_items

        """
        pass

    def test_contract_group_list(self):
        """Test case for contract_group_list

        """
        pass

    def test_contract_group_suggest(self):
        """Test case for contract_group_suggest

        """
        pass

    def test_contract_item(self):
        """Test case for contract_item

        """
        pass

    def test_contract_items(self):
        """Test case for contract_items

        """
        pass

    def test_contract_l_dependents(self):
        """Test case for contract_l_dependents

        """
        pass

    def test_contract_maturity_dependents(self):
        """Test case for contract_maturity_dependents

        """
        pass

    def test_contract_maturity_item(self):
        """Test case for contract_maturity_item

        """
        pass

    def test_contract_maturity_items(self):
        """Test case for contract_maturity_items

        """
        pass

    def test_contract_maturity_l_dependents(self):
        """Test case for contract_maturity_l_dependents

        """
        pass

    def test_contract_suggest(self):
        """Test case for contract_suggest

        """
        pass

    def test_currency_find(self):
        """Test case for currency_find

        """
        pass

    def test_currency_item(self):
        """Test case for currency_item

        """
        pass

    def test_currency_items(self):
        """Test case for currency_items

        """
        pass

    def test_currency_list(self):
        """Test case for currency_list

        """
        pass

    def test_currency_rate_dependents(self):
        """Test case for currency_rate_dependents

        """
        pass

    def test_currency_rate_item(self):
        """Test case for currency_rate_item

        """
        pass

    def test_currency_rate_items(self):
        """Test case for currency_rate_items

        """
        pass

    def test_currency_rate_l_dependents(self):
        """Test case for currency_rate_l_dependents

        """
        pass

    def test_currency_rate_list(self):
        """Test case for currency_rate_list

        """
        pass

    def test_currency_suggest(self):
        """Test case for currency_suggest

        """
        pass

    def test_exchange_find(self):
        """Test case for exchange_find

        """
        pass

    def test_exchange_item(self):
        """Test case for exchange_item

        """
        pass

    def test_exchange_items(self):
        """Test case for exchange_items

        """
        pass

    def test_exchange_list(self):
        """Test case for exchange_list

        """
        pass

    def test_exchange_suggest(self):
        """Test case for exchange_suggest

        """
        pass

    def test_get_product_fee_params(self):
        """Test case for get_product_fee_params

        """
        pass

    def test_product_dependents(self):
        """Test case for product_dependents

        """
        pass

    def test_product_find(self):
        """Test case for product_find

        """
        pass

    def test_product_item(self):
        """Test case for product_item

        """
        pass

    def test_product_items(self):
        """Test case for product_items

        """
        pass

    def test_product_l_dependents(self):
        """Test case for product_l_dependents

        """
        pass

    def test_product_list(self):
        """Test case for product_list

        """
        pass

    def test_product_session_dependents(self):
        """Test case for product_session_dependents

        """
        pass

    def test_product_session_item(self):
        """Test case for product_session_item

        """
        pass

    def test_product_session_items(self):
        """Test case for product_session_items

        """
        pass

    def test_product_session_l_dependents(self):
        """Test case for product_session_l_dependents

        """
        pass

    def test_product_suggest(self):
        """Test case for product_suggest

        """
        pass

    def test_roll_contract(self):
        """Test case for roll_contract

        """
        pass

    def test_spread_definition_item(self):
        """Test case for spread_definition_item

        """
        pass

    def test_spread_definition_items(self):
        """Test case for spread_definition_items

        """
        pass


if __name__ == '__main__':
    unittest.main()
