"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.configuration_api import ConfigurationApi  # noqa: E501


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = ConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_alert_find(self):
        """Test case for admin_alert_find

        """
        pass

    def test_admin_alert_item(self):
        """Test case for admin_alert_item

        """
        pass

    def test_admin_alert_items(self):
        """Test case for admin_alert_items

        """
        pass

    def test_admin_alert_list(self):
        """Test case for admin_alert_list

        """
        pass

    def test_admin_alert_suggest(self):
        """Test case for admin_alert_suggest

        """
        pass

    def test_clearing_house_find(self):
        """Test case for clearing_house_find

        """
        pass

    def test_clearing_house_item(self):
        """Test case for clearing_house_item

        """
        pass

    def test_clearing_house_items(self):
        """Test case for clearing_house_items

        """
        pass

    def test_clearing_house_list(self):
        """Test case for clearing_house_list

        """
        pass

    def test_clearing_house_suggest(self):
        """Test case for clearing_house_suggest

        """
        pass

    def test_entitlement_item(self):
        """Test case for entitlement_item

        """
        pass

    def test_entitlement_items(self):
        """Test case for entitlement_items

        """
        pass

    def test_entitlement_list(self):
        """Test case for entitlement_list

        """
        pass

    def test_order_strategy_type_find(self):
        """Test case for order_strategy_type_find

        """
        pass

    def test_order_strategy_type_item(self):
        """Test case for order_strategy_type_item

        """
        pass

    def test_order_strategy_type_items(self):
        """Test case for order_strategy_type_items

        """
        pass

    def test_order_strategy_type_list(self):
        """Test case for order_strategy_type_list

        """
        pass

    def test_order_strategy_type_suggest(self):
        """Test case for order_strategy_type_suggest

        """
        pass

    def test_property_find(self):
        """Test case for property_find

        """
        pass

    def test_property_item(self):
        """Test case for property_item

        """
        pass

    def test_property_items(self):
        """Test case for property_items

        """
        pass

    def test_property_list(self):
        """Test case for property_list

        """
        pass

    def test_property_suggest(self):
        """Test case for property_suggest

        """
        pass


if __name__ == '__main__':
    unittest.main()
