"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_trading_permission(self):
        """Test case for accept_trading_permission

        """
        pass

    def test_activate_second_market_data_subscription_renewal(self):
        """Test case for activate_second_market_data_subscription_renewal

        """
        pass

    def test_add_entitlement_subscription(self):
        """Test case for add_entitlement_subscription

        """
        pass

    def test_add_market_data_subscription(self):
        """Test case for add_market_data_subscription

        """
        pass

    def test_add_second_market_data_subscription(self):
        """Test case for add_second_market_data_subscription

        """
        pass

    def test_add_tradovate_subscription(self):
        """Test case for add_tradovate_subscription

        """
        pass

    def test_cancel_second_market_data_subscription(self):
        """Test case for cancel_second_market_data_subscription

        """
        pass

    def test_cancel_second_market_data_subscription_renewal(self):
        """Test case for cancel_second_market_data_subscription_renewal

        """
        pass

    def test_cancel_tradovate_subscription(self):
        """Test case for cancel_tradovate_subscription

        """
        pass

    def test_contact_info_dependents(self):
        """Test case for contact_info_dependents

        """
        pass

    def test_contact_info_item(self):
        """Test case for contact_info_item

        """
        pass

    def test_contact_info_items(self):
        """Test case for contact_info_items

        """
        pass

    def test_contact_info_l_dependents(self):
        """Test case for contact_info_l_dependents

        """
        pass

    def test_get_account_trading_permissions(self):
        """Test case for get_account_trading_permissions

        """
        pass

    def test_get_second_market_data_subscription_cost(self):
        """Test case for get_second_market_data_subscription_cost

        """
        pass

    def test_market_data_subscription_create(self):
        """Test case for market_data_subscription_create

        """
        pass

    def test_market_data_subscription_dependents(self):
        """Test case for market_data_subscription_dependents

        """
        pass

    def test_market_data_subscription_item(self):
        """Test case for market_data_subscription_item

        """
        pass

    def test_market_data_subscription_items(self):
        """Test case for market_data_subscription_items

        """
        pass

    def test_market_data_subscription_l_dependents(self):
        """Test case for market_data_subscription_l_dependents

        """
        pass

    def test_market_data_subscription_list(self):
        """Test case for market_data_subscription_list

        """
        pass

    def test_market_data_subscription_update(self):
        """Test case for market_data_subscription_update

        """
        pass

    def test_modify_credentials(self):
        """Test case for modify_credentials

        """
        pass

    def test_modify_email_address(self):
        """Test case for modify_email_address

        """
        pass

    def test_modify_password(self):
        """Test case for modify_password

        """
        pass

    def test_open_demo_account(self):
        """Test case for open_demo_account

        """
        pass

    def test_organization_find(self):
        """Test case for organization_find

        """
        pass

    def test_organization_item(self):
        """Test case for organization_item

        """
        pass

    def test_organization_items(self):
        """Test case for organization_items

        """
        pass

    def test_organization_list(self):
        """Test case for organization_list

        """
        pass

    def test_organization_suggest(self):
        """Test case for organization_suggest

        """
        pass

    def test_request_trading_permission(self):
        """Test case for request_trading_permission

        """
        pass

    def test_revoke_trading_permission(self):
        """Test case for revoke_trading_permission

        """
        pass

    def test_second_market_data_subscription_dependents(self):
        """Test case for second_market_data_subscription_dependents

        """
        pass

    def test_second_market_data_subscription_item(self):
        """Test case for second_market_data_subscription_item

        """
        pass

    def test_second_market_data_subscription_items(self):
        """Test case for second_market_data_subscription_items

        """
        pass

    def test_second_market_data_subscription_l_dependents(self):
        """Test case for second_market_data_subscription_l_dependents

        """
        pass

    def test_second_market_data_subscription_list(self):
        """Test case for second_market_data_subscription_list

        """
        pass

    def test_sign_up_organization_member(self):
        """Test case for sign_up_organization_member

        """
        pass

    def test_sync_request(self):
        """Test case for sync_request

        """
        pass

    def test_tradovate_subscription_create(self):
        """Test case for tradovate_subscription_create

        """
        pass

    def test_tradovate_subscription_dependents(self):
        """Test case for tradovate_subscription_dependents

        """
        pass

    def test_tradovate_subscription_item(self):
        """Test case for tradovate_subscription_item

        """
        pass

    def test_tradovate_subscription_items(self):
        """Test case for tradovate_subscription_items

        """
        pass

    def test_tradovate_subscription_l_dependents(self):
        """Test case for tradovate_subscription_l_dependents

        """
        pass

    def test_tradovate_subscription_list(self):
        """Test case for tradovate_subscription_list

        """
        pass

    def test_tradovate_subscription_update(self):
        """Test case for tradovate_subscription_update

        """
        pass

    def test_user_find(self):
        """Test case for user_find

        """
        pass

    def test_user_item(self):
        """Test case for user_item

        """
        pass

    def test_user_items(self):
        """Test case for user_items

        """
        pass

    def test_user_list(self):
        """Test case for user_list

        """
        pass

    def test_user_plugin_create(self):
        """Test case for user_plugin_create

        """
        pass

    def test_user_plugin_dependents(self):
        """Test case for user_plugin_dependents

        """
        pass

    def test_user_plugin_item(self):
        """Test case for user_plugin_item

        """
        pass

    def test_user_plugin_items(self):
        """Test case for user_plugin_items

        """
        pass

    def test_user_plugin_l_dependents(self):
        """Test case for user_plugin_l_dependents

        """
        pass

    def test_user_plugin_list(self):
        """Test case for user_plugin_list

        """
        pass

    def test_user_plugin_update(self):
        """Test case for user_plugin_update

        """
        pass

    def test_user_property_dependents(self):
        """Test case for user_property_dependents

        """
        pass

    def test_user_property_item(self):
        """Test case for user_property_item

        """
        pass

    def test_user_property_items(self):
        """Test case for user_property_items

        """
        pass

    def test_user_property_l_dependents(self):
        """Test case for user_property_l_dependents

        """
        pass

    def test_user_session_item(self):
        """Test case for user_session_item

        """
        pass

    def test_user_session_items(self):
        """Test case for user_session_items

        """
        pass

    def test_user_session_stats_dependents(self):
        """Test case for user_session_stats_dependents

        """
        pass

    def test_user_session_stats_item(self):
        """Test case for user_session_stats_item

        """
        pass

    def test_user_session_stats_items(self):
        """Test case for user_session_stats_items

        """
        pass

    def test_user_session_stats_l_dependents(self):
        """Test case for user_session_stats_l_dependents

        """
        pass

    def test_user_session_stats_list(self):
        """Test case for user_session_stats_list

        """
        pass

    def test_user_suggest(self):
        """Test case for user_suggest

        """
        pass


if __name__ == '__main__':
    unittest.main()
