"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.alerts_api import AlertsApi  # noqa: E501


class TestAlertsApi(unittest.TestCase):
    """AlertsApi unit test stubs"""

    def setUp(self):
        self.api = AlertsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_alert_signal_dependents(self):
        """Test case for admin_alert_signal_dependents

        """
        pass

    def test_admin_alert_signal_item(self):
        """Test case for admin_alert_signal_item

        """
        pass

    def test_admin_alert_signal_items(self):
        """Test case for admin_alert_signal_items

        """
        pass

    def test_admin_alert_signal_l_dependents(self):
        """Test case for admin_alert_signal_l_dependents

        """
        pass

    def test_admin_alert_signal_list(self):
        """Test case for admin_alert_signal_list

        """
        pass

    def test_alert_dependents(self):
        """Test case for alert_dependents

        """
        pass

    def test_alert_item(self):
        """Test case for alert_item

        """
        pass

    def test_alert_items(self):
        """Test case for alert_items

        """
        pass

    def test_alert_l_dependents(self):
        """Test case for alert_l_dependents

        """
        pass

    def test_alert_list(self):
        """Test case for alert_list

        """
        pass

    def test_alert_signal_dependents(self):
        """Test case for alert_signal_dependents

        """
        pass

    def test_alert_signal_item(self):
        """Test case for alert_signal_item

        """
        pass

    def test_alert_signal_items(self):
        """Test case for alert_signal_items

        """
        pass

    def test_alert_signal_l_dependents(self):
        """Test case for alert_signal_l_dependents

        """
        pass

    def test_alert_signal_list(self):
        """Test case for alert_signal_list

        """
        pass

    def test_complete_alert_signal(self):
        """Test case for complete_alert_signal

        """
        pass

    def test_create_alert(self):
        """Test case for create_alert

        """
        pass

    def test_delete_alert(self):
        """Test case for delete_alert

        """
        pass

    def test_dismiss_alert(self):
        """Test case for dismiss_alert

        """
        pass

    def test_mark_read_alert_signal(self):
        """Test case for mark_read_alert_signal

        """
        pass

    def test_modify_alert(self):
        """Test case for modify_alert

        """
        pass

    def test_reset_alert(self):
        """Test case for reset_alert

        """
        pass

    def test_take_alert_signal_ownership(self):
        """Test case for take_alert_signal_ownership

        """
        pass


if __name__ == '__main__':
    unittest.main()
