"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.product_margin import ProductMargin
globals()['ProductMargin'] = ProductMargin
from openapi_client.model.product_fee_params import ProductFeeParams


class TestProductFeeParams(unittest.TestCase):
    """ProductFeeParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductFeeParams(self):
        """Test ProductFeeParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProductFeeParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
