"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.trade_date import TradeDate
globals()['TradeDate'] = TradeDate
from openapi_client.model.market_data_subscription_plan import MarketDataSubscriptionPlan


class TestMarketDataSubscriptionPlan(unittest.TestCase):
    """MarketDataSubscriptionPlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarketDataSubscriptionPlan(self):
        """Test MarketDataSubscriptionPlan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MarketDataSubscriptionPlan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
