"""
    Tradovate API

    Tradovate API provides an access to the complete set of robust Tradovate functionality.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from openapi_client.model.account import Account
    from openapi_client.model.cash_balance import CashBalance
    from openapi_client.model.command import Command
    from openapi_client.model.command_report import CommandReport
    from openapi_client.model.contract import Contract
    from openapi_client.model.contract_group import ContractGroup
    from openapi_client.model.contract_maturity import ContractMaturity
    from openapi_client.model.currency import Currency
    from openapi_client.model.exchange import Exchange
    from openapi_client.model.execution_report import ExecutionReport
    from openapi_client.model.fill import Fill
    from openapi_client.model.fill_pair import FillPair
    from openapi_client.model.margin_snapshot import MarginSnapshot
    from openapi_client.model.model_property import ModelProperty
    from openapi_client.model.order import Order
    from openapi_client.model.order_strategy import OrderStrategy
    from openapi_client.model.order_strategy_link import OrderStrategyLink
    from openapi_client.model.order_strategy_type import OrderStrategyType
    from openapi_client.model.order_version import OrderVersion
    from openapi_client.model.position import Position
    from openapi_client.model.product import Product
    from openapi_client.model.spread_definition import SpreadDefinition
    from openapi_client.model.user import User
    from openapi_client.model.user_account_auto_liq import UserAccountAutoLiq
    from openapi_client.model.user_plugin import UserPlugin
    from openapi_client.model.user_property import UserProperty
    globals()['Account'] = Account
    globals()['CashBalance'] = CashBalance
    globals()['Command'] = Command
    globals()['CommandReport'] = CommandReport
    globals()['Contract'] = Contract
    globals()['ContractGroup'] = ContractGroup
    globals()['ContractMaturity'] = ContractMaturity
    globals()['Currency'] = Currency
    globals()['Exchange'] = Exchange
    globals()['ExecutionReport'] = ExecutionReport
    globals()['Fill'] = Fill
    globals()['FillPair'] = FillPair
    globals()['MarginSnapshot'] = MarginSnapshot
    globals()['ModelProperty'] = ModelProperty
    globals()['Order'] = Order
    globals()['OrderStrategy'] = OrderStrategy
    globals()['OrderStrategyLink'] = OrderStrategyLink
    globals()['OrderStrategyType'] = OrderStrategyType
    globals()['OrderVersion'] = OrderVersion
    globals()['Position'] = Position
    globals()['Product'] = Product
    globals()['SpreadDefinition'] = SpreadDefinition
    globals()['User'] = User
    globals()['UserAccountAutoLiq'] = UserAccountAutoLiq
    globals()['UserPlugin'] = UserPlugin
    globals()['UserProperty'] = UserProperty


class SyncMessage(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'users': ([User],),  # noqa: E501
            'contract_groups': ([ContractGroup],),  # noqa: E501
            'accounts': ([Account],),  # noqa: E501
            'margin_snapshots': ([MarginSnapshot],),  # noqa: E501
            'user_account_auto_liqs': ([UserAccountAutoLiq],),  # noqa: E501
            'cash_balances': ([CashBalance],),  # noqa: E501
            'currencies': ([Currency],),  # noqa: E501
            'positions': ([Position],),  # noqa: E501
            'fill_pairs': ([FillPair],),  # noqa: E501
            'orders': ([Order],),  # noqa: E501
            'contracts': ([Contract],),  # noqa: E501
            'contract_maturities': ([ContractMaturity],),  # noqa: E501
            'products': ([Product],),  # noqa: E501
            'exchanges': ([Exchange],),  # noqa: E501
            'spread_definitions': ([SpreadDefinition],),  # noqa: E501
            'commands': ([Command],),  # noqa: E501
            'command_reports': ([CommandReport],),  # noqa: E501
            'execution_reports': ([ExecutionReport],),  # noqa: E501
            'order_versions': ([OrderVersion],),  # noqa: E501
            'fills': ([Fill],),  # noqa: E501
            'order_strategies': ([OrderStrategy],),  # noqa: E501
            'order_strategy_links': ([OrderStrategyLink],),  # noqa: E501
            'user_properties': ([UserProperty],),  # noqa: E501
            'properties': ([ModelProperty],),  # noqa: E501
            'user_plugins': ([UserPlugin],),  # noqa: E501
            'order_strategy_types': ([OrderStrategyType],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'users': 'users',  # noqa: E501
        'contract_groups': 'contractGroups',  # noqa: E501
        'accounts': 'accounts',  # noqa: E501
        'margin_snapshots': 'marginSnapshots',  # noqa: E501
        'user_account_auto_liqs': 'userAccountAutoLiqs',  # noqa: E501
        'cash_balances': 'cashBalances',  # noqa: E501
        'currencies': 'currencies',  # noqa: E501
        'positions': 'positions',  # noqa: E501
        'fill_pairs': 'fillPairs',  # noqa: E501
        'orders': 'orders',  # noqa: E501
        'contracts': 'contracts',  # noqa: E501
        'contract_maturities': 'contractMaturities',  # noqa: E501
        'products': 'products',  # noqa: E501
        'exchanges': 'exchanges',  # noqa: E501
        'spread_definitions': 'spreadDefinitions',  # noqa: E501
        'commands': 'commands',  # noqa: E501
        'command_reports': 'commandReports',  # noqa: E501
        'execution_reports': 'executionReports',  # noqa: E501
        'order_versions': 'orderVersions',  # noqa: E501
        'fills': 'fills',  # noqa: E501
        'order_strategies': 'orderStrategies',  # noqa: E501
        'order_strategy_links': 'orderStrategyLinks',  # noqa: E501
        'user_properties': 'userProperties',  # noqa: E501
        'properties': 'properties',  # noqa: E501
        'user_plugins': 'userPlugins',  # noqa: E501
        'order_strategy_types': 'orderStrategyTypes',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, users, contract_groups, *args, **kwargs):  # noqa: E501
        """SyncMessage - a model defined in OpenAPI

        Args:
            users ([User]):
            contract_groups ([ContractGroup]):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            accounts ([Account]): [optional]  # noqa: E501
            margin_snapshots ([MarginSnapshot]): [optional]  # noqa: E501
            user_account_auto_liqs ([UserAccountAutoLiq]): [optional]  # noqa: E501
            cash_balances ([CashBalance]): [optional]  # noqa: E501
            currencies ([Currency]): [optional]  # noqa: E501
            positions ([Position]): [optional]  # noqa: E501
            fill_pairs ([FillPair]): [optional]  # noqa: E501
            orders ([Order]): [optional]  # noqa: E501
            contracts ([Contract]): [optional]  # noqa: E501
            contract_maturities ([ContractMaturity]): [optional]  # noqa: E501
            products ([Product]): [optional]  # noqa: E501
            exchanges ([Exchange]): [optional]  # noqa: E501
            spread_definitions ([SpreadDefinition]): [optional]  # noqa: E501
            commands ([Command]): [optional]  # noqa: E501
            command_reports ([CommandReport]): [optional]  # noqa: E501
            execution_reports ([ExecutionReport]): [optional]  # noqa: E501
            order_versions ([OrderVersion]): [optional]  # noqa: E501
            fills ([Fill]): [optional]  # noqa: E501
            order_strategies ([OrderStrategy]): [optional]  # noqa: E501
            order_strategy_links ([OrderStrategyLink]): [optional]  # noqa: E501
            user_properties ([UserProperty]): [optional]  # noqa: E501
            properties ([ModelProperty]): [optional]  # noqa: E501
            user_plugins ([UserPlugin]): [optional]  # noqa: E501
            order_strategy_types ([OrderStrategyType]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.users = users
        self.contract_groups = contract_groups
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
